### ISSUE TITLE
Issue languages should be based on their repository's language rather than name

### ISSUE THREAD

**Issue by andrew** [ipfs-shipyard/ecosystem-dashboard#24]
IPFS prefixes most repos with go- or js- but that doesn't work in all cases and when filtering by language some repos may fall through the cracks, instead each issue/pr should have the language field denormalized from it's repository.

**Comment by SgtPooki** [comment]
@andrew , i'm new to the ecosystem-dashboard, but interested in polishing it since it seems like we rely on it quite often. 

It sounds like you're saying the ecosystem-dashboard's language filter identifies an issues' language based on the prefixed language name of the github repository that the issue is opened for. Your proposal seems to suggest we need to somehow recognize which language each individual issue is related to, and filter by that instead. Am I understanding correctly? 

If so, how do you recommend we determine the language for each issue?

**Comment by andrew** [comment]
@SgtPooki we have the main language for each repo stored in the repositories table (https://github.com/ipfs-shipyard/ecosystem-dashboard/blob/master/db/schema.rb#L194) so it would be pretty easy to join that when filtering or we could denormalize the language field onto the issues table which would be a little more performant.

**Comment by andrew** [comment]
Done in https://github.com/ipfs-shipyard/ecosystem-dashboard/commit/d5fe443bab21c8b14797980c3847fb49931a0e95
