### ISSUE TITLE
What is /packages supposed to tell me?

### ISSUE THREAD

**Issue by BigLep** [ipfs-shipyard/ecosystem-dashboard#409]
I'm looking at https://ipfs.ecosystem-dashboard.com/packages/2097 for js-ipfs.  I'm curious how many other packages are depending on it.

I see ``Dependent Repositories: 1965``

When I go to https://libraries.io/npm/ipfs or https://www.npmjs.com/package/ipfs I see much smaller numbers (<500).

In general, are there docs/info on how /packages works and what data source(s) it's using?

Thanks!

**Comment by andrew** [comment]
Dependent repositories is a different number to dependent packages (like you would see on npmjs.com), it's all software repositories that declare js-ipfs as a dependency, including applications that wouldn't be published on npm. 

Ecosystem dashboard works in a very similar way to Libraries.io (I built libraries.io and sold it a few years ago, it has since been neglected hence the low numbers), it scans the contents of repositories on GitHub looking for package.json and package-lock.json files and then parses them and records what it finds. 

Ecosystem dashboard does a few extra things to make sure it finds and scans as many web3 repos as possible, including doing code and issue searches for "ipfs" and "filecoin" on a very regular basis and also scanning all repos from known collabortor orgs and any contributors to core projects.

**Comment by BigLep** [comment]
Thanks @andrew .  All makes sense.  My apologies too if this is in docs somewhere and I missed it.  

Closing for now since I don't have further questions.
