### ISSUE TITLE
Bug? Filter view is still including a closed issue

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs-shipyard/ecosystem-dashboard#82]
This URL:
https://ecosystem-research.herokuapp.com/all?repo_full_name%5B%5D=ipfs-shipyard%2Fipfs-webui&repo_full_name%5B%5D=ipfs-shipyard%2Fipfs-desktop&repo_full_name%5B%5D=ipfs%2Fpublic-gateway-checker&repo_full_name%5B%5D=ipfs%2Fdir-index-html&repo_full_name%5B%5D=ipfs-shipyard%2Fipld-explorer&repo_full_name%5B%5D=ipfs-shipyard%2Fipld-explorer-components&repo_full_name%5B%5D=ipfs%2Fdistributions&repo_full_name%5B%5D=ipfs-shipyard%2Fipfs-companion&repo_full_name%5B%5D=ipfs%2Fipfs-gui&repo_full_name%5B%5D=ipfs-shipyard%2Fi18n&repo_full_name%5B%5D=ipfs-shipyard%2Fipfs-css&repo_full_name%5B%5D=ipfs-shipyard%2Fipfs-share-files&repo_full_name%5B%5D=ipfs-shipyard%2Fipfs-ui-style-guide&state=open
... is intended to filter "state=open", but it's currently including the following closed issue:
https://github.com/ipfs-shipyard/ipfs-desktop/issues/1621

Not certain why.

**Comment by andrew** [comment]
Oh, something is broken with the syncing there, will investigate tomorrow morning

**Comment by andrew** [comment]
I've fixed up one syncing bug that I accidentally introduced last week, but it didn't automatically fix this one, looks like the problem stems from that issue being transferred between repos, need to make sure that the repo name is updated in the dashboards database after syncing it.

**Comment by andrew** [comment]
Ok pinned down the problem, when an issue gets transferred between repos, it actually ends up with a different id in GitHub's database, so to ecosystem dashboard they look like two different issues, which both attempt to get updated and then fail, so we're left with one correct, closed one and one incorrect open one that won't save anymore because it's a duplicate.

Need to write something that catches that race condition when syncing and deletes the old one.

**Comment by andrew** [comment]
Think I've squashed it now, let me know if you see any more oddballs

**Comment by jessicaschilling** [comment]
Thank you!
